# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnis < Formula
  desc "Multi-agent harness: CLI/TUI (omnis) + HTTP API & Web UI server (omnis-server)"
  homepage "https://github.com/blouargant/omnis"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.2/omnis_1.5.2_Darwin_x86_64.tar.gz"
      sha256 "c84842d595a5f73dcd9340eab51468ee6f6eee5faf36da371359d4d7609f422d"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.2/omnis_1.5.2_Darwin_arm64.tar.gz"
      sha256 "b29705d86f0e5920edea7dfdcfce94a97af5c644928adb3662a1f93d9147db5c"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.2/omnis_1.5.2_Linux_x86_64.tar.gz"
      sha256 "d50e2d717e7a10d0c32243839efe8d7d60cb9d33cc26f69913a6cacdd03a0207"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.2/omnis_1.5.2_Linux_arm64.tar.gz"
      sha256 "209ce37eeeec0a979c2c056556c6ec508db6752988ae983ec3d19b8b3f6d75d3"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  def caveats
    <<~EOS
      Bundled agents, skills and the Web UI install under
        #{HOMEBREW_PREFIX}/share/omnis
      and are refreshed on every `brew upgrade`. Put your own overrides in
        ~/.omnis   (e.g. ~/.omnis/agents.json, ~/.omnis/models.json)
      which take precedence over the bundled defaults.

      Set a provider API key before first run, e.g.:
        export ANTHROPIC_API_KEY=sk-...

      Run the Web UI / HTTP API server (listens on :8080, unauthenticated by
      default — set OMNIS_SERVER_TOKEN to require a bearer token):
        omnis-server
      or as a background service:
        brew services start omnis
    EOS
  end

  service do
    run [opt_bin/"omnis-server"]
    keep_alive true
    log_path var/"log/omnis-server.log"
    error_log_path var/"log/omnis-server.log"
    working_dir var
  end

  test do
    system bin/"omnis", "version"
  end
end
