# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omnis < Formula
  desc "Multi-agent harness: CLI/TUI (omnis) + HTTP API & Web UI server (omnis-server)"
  homepage "https://github.com/blouargant/omnis"
  version "1.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.3/omnis_1.5.3_Darwin_x86_64.tar.gz"
      sha256 "776c0384e0986683f91931a29348909591ffe611a269f6f7fe78c008f7b92643"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.3/omnis_1.5.3_Darwin_arm64.tar.gz"
      sha256 "9cd751bac697e5413269cbc2d1d8ff4caf99990d9523f3f75af85ad14db04226"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.3/omnis_1.5.3_Linux_x86_64.tar.gz"
      sha256 "5a6ba21703ee4aa882c0c5dc73cbad0370f32c204760c1e2ef1ad21a4fd93a80"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/omnis/releases/download/v1.5.3/omnis_1.5.3_Linux_arm64.tar.gz"
      sha256 "e7d8d5e15c225094cf67b7434f6c435a9416dbaa56a90a0ab59d7212126de5e0"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so omnis finds the bundled web assets + config without the user
        # setting anything. OMNIS_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.omnis intact.
        libexec.install "omnis", "omnis-server"
        (bin/"omnis").write_env_script libexec/"omnis",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"omnis-server").write_env_script libexec/"omnis-server",
          OMNIS_WEB_DIR:           pkgshare/"web",
          OMNIS_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.omnis (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  def caveats
    <<~EOS
      Bundled agents, skills and the Web UI install under
        #{HOMEBREW_PREFIX}/share/omnis
      and are refreshed on every `brew upgrade`. Put your own overrides in
        ~/.omnis   (e.g. ~/.omnis/agents.json, ~/.omnis/models.json)
      which take precedence over the bundled defaults.

      Set a provider API key before first run, e.g.:
        export ANTHROPIC_API_KEY=sk-...

      Run the Web UI / HTTP API server (listens on :8080, unauthenticated by
      default — set OMNIS_SERVER_TOKEN to require a bearer token):
        omnis-server
      or as a background service:
        brew services start omnis
    EOS
  end

  service do
    run [opt_bin/"omnis-server"]
    keep_alive true
    log_path var/"log/omnis-server.log"
    error_log_path var/"log/omnis-server.log"
    working_dir var
  end

  test do
    system bin/"omnis", "version"
  end
end
