# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yoke < Formula
  desc "Multi-agent harness: CLI/TUI (yoke) + HTTP API & Web UI server (yoke-server)"
  homepage "https://github.com/blouargant/yoke"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blouargant/yoke/releases/download/v1.1.2/yoke_1.1.2_Darwin_x86_64.tar.gz"
      sha256 "cd9038c0d9b8aeac2f0beec7030909cf9f2c27ee5c63a8713c92a44bf3f5fc8a"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blouargant/yoke/releases/download/v1.1.2/yoke_1.1.2_Darwin_arm64.tar.gz"
      sha256 "f1f01d23cf8104b06e5941803f58f25046c82d34ac8ca8458c38fb8445094c42"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/yoke/releases/download/v1.1.2/yoke_1.1.2_Linux_x86_64.tar.gz"
      sha256 "08ad19c6987f5c4ca22c9b224047f551e21481cbfa11b4ff13f46a8fd129e18e"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/yoke/releases/download/v1.1.2/yoke_1.1.2_Linux_arm64.tar.gz"
      sha256 "a7da07c568d1f8284b0c554d468569076fdc71a75af937917e439b40cae834e4"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  def caveats
    <<~EOS
      Bundled agents, skills and the Web UI install under
        #{HOMEBREW_PREFIX}/share/yoke
      and are refreshed on every `brew upgrade`. Put your own overrides in
        ~/.yoke   (e.g. ~/.yoke/agents.json, ~/.yoke/models.json)
      which take precedence over the bundled defaults.

      Set a provider API key before first run, e.g.:
        export ANTHROPIC_API_KEY=sk-...

      Run the Web UI / HTTP API server (listens on :8080, unauthenticated by
      default — set YOKE_SERVER_TOKEN to require a bearer token):
        yoke-server
      or as a background service:
        brew services start yoke
    EOS
  end

  service do
    run [opt_bin/"yoke-server"]
    keep_alive true
    log_path var/"log/yoke-server.log"
    error_log_path var/"log/yoke-server.log"
    working_dir var
  end

  test do
    system bin/"yoke", "version"
  end
end
