# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yoke < Formula
  desc "Multi-agent harness: CLI/TUI (yoke) + HTTP API & Web UI server (yoke-server)"
  homepage "https://github.com/blouargant/yoke"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blouargant/yoke/releases/download/v1.2.0/yoke_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "d1f18220a498cdb5f82e8efcdaadf272717e8f32945861a4156f1c8f81878658"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blouargant/yoke/releases/download/v1.2.0/yoke_1.2.0_Darwin_arm64.tar.gz"
      sha256 "e8ded22c0155c9893e21e9f0a14becc68ab1d6d67acdba57c85e11fba796180f"

      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/yoke/releases/download/v1.2.0/yoke_1.2.0_Linux_x86_64.tar.gz"
      sha256 "3567aad4fabc4feb8462310b882933beb037b4f0aa791bf8c11fa1ceb32ad5e1"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blouargant/yoke/releases/download/v1.2.0/yoke_1.2.0_Linux_arm64.tar.gz"
      sha256 "0bd57e15f038ed701d618bcfffce42e3c81e18b9074102a0f5eeba07772310fe"
      define_method(:install) do
        # Keep the real binaries in libexec; expose env-injecting wrappers on
        # PATH so yoke finds the bundled web assets + config without the user
        # setting anything. YOKE_SYSTEM_CONFIG_DIR relocates only the system
        # layer of the config search chain, leaving ./.agents and ~/.yoke intact.
        libexec.install "yoke", "yoke-server"
        (bin/"yoke").write_env_script libexec/"yoke",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare
        (bin/"yoke-server").write_env_script libexec/"yoke-server",
          YOKE_WEB_DIR:           pkgshare/"web",
          YOKE_SYSTEM_CONFIG_DIR: pkgshare

        # Bundled defaults, refreshed on every `brew upgrade`. User overrides
        # live in ~/.yoke (higher precedence) so upgrades never clobber them.
        pkgshare.install "web"
        pkgshare.install "registry"
        pkgshare.install Dir["config/*.json"]
        pkgshare.install "config/server.yaml"
        (pkgshare/"filters").install Dir["config/filters/*.json"]
      end
    end
  end

  def caveats
    <<~EOS
      Bundled agents, skills and the Web UI install under
        #{HOMEBREW_PREFIX}/share/yoke
      and are refreshed on every `brew upgrade`. Put your own overrides in
        ~/.yoke   (e.g. ~/.yoke/agents.json, ~/.yoke/models.json)
      which take precedence over the bundled defaults.

      Set a provider API key before first run, e.g.:
        export ANTHROPIC_API_KEY=sk-...

      Run the Web UI / HTTP API server (listens on :8080, unauthenticated by
      default — set YOKE_SERVER_TOKEN to require a bearer token):
        yoke-server
      or as a background service:
        brew services start yoke
    EOS
  end

  service do
    run [opt_bin/"yoke-server"]
    keep_alive true
    log_path var/"log/yoke-server.log"
    error_log_path var/"log/yoke-server.log"
    working_dir var
  end

  test do
    system bin/"yoke", "version"
  end
end
